# colors
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)

BACKGROUND_COLOR = WHITE

# window
WINDOW_POSITION_X = 100
WINDOW_POSITION_Y = 100

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

WINDOW_PADDING = 15

WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)

# image paths
PLAYER_SPRITE_IMAGE_PATH = './img/main_sprite.jpg'
ARROW_SPRITE_IMAGE_PATH = './img/arrow_sprite.png'

# fonts
monospace_12 = ['monospace', 12]


# player
PLAYER_SPEED = 7
INIT_PLAYER_X = 30
INIT_PLAYER_Y = 50

TIME_UNIT = 0.1

MAX_ARROWS_COUNT = 40
